package: yform_usability
version: '1.10.6'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/yform_usability
compile: 0

requires:
    php:
        version: '>=7, <9'
    packages:
        yform/manager: '>=2,<4'

pages:
    yform/manager/usability:
        title: 'Usability'
        perm: admin[]

default_config:
    duplicate_tables: NULL
    sorting_tables: NULL
    status_tables: NULL
    duplicate_tables_all: '|1|'
    sorting_tables_all: '|1|'
    status_tables_all: '|1|'
    use_inline_search: NULL
