package: yform_usability
version: '1.10.6'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/yform_usability
compile: 0

requires:
    php:
        version: '>=7, <9'
    packages:
        yform/manager: '>=2,<4'

pages:
    yform/manager/usability:
        title: 'Usability'
        perm: admin[]

default_config:
    duplicate_tables: '["all"]'
    sorting_tables: '["all"]'
    status_tables: '["all"]'
