package: yform_usability
version: '2.0-beta1'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/yform_usability
compile: 0

requires:
    php:
        version: '>=7, <9'
    packages:
        yform/manager: '^4'

pages:
    yform/manager/usability:
        title: 'Usability'
        perm: admin[]
