package: yform_usability
version: '2.1.6'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/yform_usability
compile: 0

requires:
    redaxo: '^5.14.1'
    php:
        version: '>=7, <9'
    packages:
        yform: '>=4.0.2, <6'

pages:
    yform/manager/usability:
        title: 'Usability'
        perm: admin[]
    yform/manager/usability_thumbnails:
        title: 'translate:yform_usability.thumbnail_mappings'
        perm: admin[]

default_config:
    duplicate_tables: NULL
    sorting_tables: NULL
    status_tables: NULL
    duplicate_tables_all: '|1|'
    sorting_tables_all: '|1|'
    status_tables_all: '|1|'
    use_inline_search: NULL
    status_first_column_all: NULL
    status_first_column_tables: NULL
