<?php

/**
 * This file is part of the Kreatif\Project package.
 *
 * @author Kreatif GmbH
 * @author a.platter@kreatif.it
 * Date: 06.08.21
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */


class ModYform extends rex_yform
{
    protected int   $repeaterValueId = 0;
    protected array $values          = [];
    protected array $loadedData      = [];
    protected array $formValues      = [];

    public function __construct(array $params = [])
    {
        $params['form_action']              = '';
        $params['submit_btn_show']          = false;
        $params['form_showformafterupdate'] = true;
        $params['form_ytemplate']           = 'backend,bootstrap,classic';

        parent::__construct($params);
    }

    public function getForm()
    {
        $this->setObjectparams('data', empty($_POST) ? $this->formValues : false);

        rex_set_session('yform_usability_modyform', $this);
        return parent::getForm(); // TODO: Change the autogenerated stub
    }

    public function setValueField($type = '', $values = [])
    {
        [$valueId, $name] = explode('.', $values['name']);

        if ($this->repeaterValueId > 0) {
            $values['name'] = "{$this->repeaterValueId}.{$index}.{$values['name']}";
            //$values['default'] = $item[$name] ?? $values['default'];
        }
        $this->addValueField($type, $valueId, $name, $values);
    }

    private function addValueField($type, $valueId, $name, $values)
    {
        $data = $this->loadData($valueId);

        $this->formValues["{$valueId}.{$name}"] = $data[$name];
        parent::setValueField($type, $values);
    }

    public function startRepeater(int $sliceValueId): void
    {
        $this->repeaterValueId = $sliceValueId;
    }

    public function endRepeater(): void
    {
        $this->repeaterValueId = 0;
    }

    private function loadData(int $valueId)
    {
        if (!isset($this->loadedData[$valueId])) {
            $key     = "value{$valueId}";
            $sliceId = rex_request::get('slice_id', 'int');
            $query   = \yform\usability\Model\ArticleSlice::query();
            $query->select([$key]);
            $query->where('id', $sliceId);
            $this->loadedData[$valueId] = rex_var::toArray($query->findOne()->getValue($key));
        }
        return $this->loadedData[$valueId];
    }

    public static function ext__updateSlice(rex_extension_point $ep): void
    {
        /** @var self $form */
        $form = rex_session('yform_usability_modyform');
        $form->getForm();

        if ($form->objparams['send']) {
            $values = [];
            $sql    = rex_sql::factory();
            $sql->setTable(rex::getTable('article_slice'));

            foreach ($form->objparams['value_pool']['sql'] as $key => $value) {
                [$valueId, $repeaterIndex, $name] = explode('.', $key);

                if (isset($name)) {
                    $values[$valueId][$repeaterIndex][$name] = $value;
                } else {
                    $values[$valueId][$repeaterIndex] = $value;
                }
            }
            foreach ($values as $valueId => $data) {
                $sql->setValue("value{$valueId}", json_encode($data));
            }
            $sql->setWhere('id = :id', ['id' => $ep->getParam('slice_id')]);
            $sql->update();
        }
    }
}